### ISSUE TITLE
Arrows that very obviously hit a player disappear or bounce off 

### ISSUE THREAD

**Issue by jexeI** [StratusNetwork/Issues#210]
So this has been a known issue since the OCN days, the arrow clips the fake hitbox by the player where the server has not moved the player's real zombie hitbox to where the player is visibly standing, resulting in an arrow bouncing off, or even disappearing. Arrows bouncing off is not a client side thing since I observe it happening to myself during gameplay as well as it happening to others. What makes this worse is that arrows that I shoot, if they hit someone has about a 1/3 chance of bouncing off and a 1/8th chance of just vanishing after hitting the target.

**Comment by jexeI** [comment]
This has also been happening in 1.8 and 1.7, half of not fully charged arrows end off bouncing off the hitbox of enemies.

**Comment by amactus** [comment]
Fixed with hitbox fixes

**Comment by jexeI** [comment]
@amactus it is still happening. Arrows now rarely bounce off, though I can't say they don't completely. Arrows still disappear when they look like they're about to hit a player. I'm hypothesizing that this is most likely a 1.9+ server-side to client communication error, as any client versions cannot correctly render the server's interpretation of the arrow's trajectory, leading in false arrow trajectories being shown to players.
