### ISSUE TITLE
Navigator sign does not list any servers

### ISSUE THREAD

**Issue by Marcono1234** [StratusNetwork/Issues#45]
# The bug
The "Navigator" sign does not list any servers, it only shows an option to teleport to the lobby. Since there are other servers (can be seen by having the server tab complete `/server `) I excepted them to appear in the selection.

**Comment by ShinyDialga** [comment]
Fixed by cs_

**Comment by Marcono1234** [comment]
It looks like the tournament server still does not appear in the navigator, even when there is no whitelist. Is this intended?
